# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
gcpreviews:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-go
    tag: 0.1.572
    
controllerbuild:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-go
    tag: 0.1.572
    
controllerteam:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-go
    tag: 0.1.572
    
controllerrole:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-jx
    tag: 0.1.572
    
gcactivities:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-jx
    tag: 0.1.572
    
gcpods:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-jx
    tag: 0.1.572    
    
expose:
  Image: gcr.azk8s.cn/jenkinsxio/exposecontroller


exposecontroller:
  image: 
    repository: gcr.azk8s.cn/jenkinsxio/exposecontroller

    
heapster:
  image:
    repository: gcr.azk8s.cn/google_containers/heapster
  resizer:
    image:
      repository: gcr.azk8s.cn/google_containers/addon-resizer



Ingress:
  enable: true
  image:
    repository: gcr.azk8s.cn/google_containers/defaultbackend
      
jenkins:
  Master:
    # Master Service annotations
    ServiceAnnotations:
      fabric8.io/exposeUrl: "http://jenkins.jx.xinkongjian.tech:8080"
  Agent:
    # Key Value selectors. Ex:
    # jenkins-agent: v1
    PodTemplates:
      aws-cdk:
        Containers:
          aws-cdk:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven-nodejs:0.1.350

      Maven:
        Containers:
          Maven:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-maven:0.1.572

      Maven-Java11:
        Containers:
          Maven:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven-java11:0.1.350
      Gradle:
        Containers:
          Gradle:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-gradle:0.1.572
      Scala:
        Containers:
          Scala:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-scala:0.1.572
      Go:
        Containers:
          Go:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-go:0.1.572
      Terraform:
        Containers:
          Terraform:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-terraform:0.1.572
      Rust:
        Containers:
          Rust:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-rust:0.1.572
      Newman:
        Containers:
          Newman:
            Image: gcr.azk8s.cn/jenkinsxio/builder-newman:0.1.350
      Nodejs:
        Containers:
          Nodejs:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-nodejs:0.1.572
      Maven-Nodejs:
        Containers:
          MavenNodejs:
            Image: gcr.azk8s.cn/jenkinsxio/builder-maven-nodejs:0.1.350
      JX-base:
        Containers:
          JX-base:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-jx:0.1.572
      Promote:
        Containers:
          Promote:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-jx:0.1.572
      Python2:
        Containers:
          Python:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-python2:0.1.572
      Python:
        Containers:
          Python:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-python:0.1.572
      Python37:
        Containers:
          Python:
            Image: gcr.azk8s.cn/jenkinsxio/builder-python37:0.1.350
      Ruby:
        Containers:
          Ruby:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-ruby:0.1.572
      Swift:
        Containers:
          Swift:
            Image: registry.cn-shenzhen.aliyuncs.com/xkj-jx/builder-swift:0.1.572
      Dlang:
        Containers:
          Dlang:
            Image: gcr.azk8s.cn/jenkinsxio/builder-dlang:0.1.350
  Persistence:
    ## jenkins data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # StorageClass: "-"
docker-registry:
  enabled: true
  service:
    annotations:
      fabric8.io/exposeUrl: "http://docker-registry.jx.xinkongjian.tech:8080"
      # fabric8.io/expose: "true"
      # fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx\nnginx.ingress.kubernetes.io/proxy-body-size: 2g"
  #vpersistence:
    #vaccessMode: 'ReadWriteOnce'
    #venabled: true
    #vsize: 100Gi
chartmuseum:
  enabled: true
  service:
    annotations:
      fabric8.io/exposeUrl: "http://chartmuseum.jx.xinkongjian.tech:8080"
nexus:
  enabled: true
  image:
    repository: gcr.azk8s.cn/jenkinsxio/nexus
  service:
    annotations:
      fabric8.io/exposeUrl: "http://nexus.jx.xinkongjian.tech:8080"
